server:
  port: ${PORT}

spring:
  application:
    name: gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI}


logging:
  level:
    org.springframework.cloud.gateway: DEBUG

DEBUG: true