server:
  port: 8080

spring:
  application:
    name: gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_1V4xEEg04/.well-known/jwks.json


logging:
  level:
    org.springframework.cloud.gateway: DEBUG