server:
  port: 8080

spring:
  application:
    name: gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK-SET-URI}


logging:
  level:
    org.springframework.cloud.gateway: DEBUG

DEBUG: true